name: e2e

on:
  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go1.16-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go1.16-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          name: e2e-kind-acceptance-test-cluster
          version: "v0.10.0"
          image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
      - name: kind-check
        run: |
          kubectl get pods -A
      # - name: Setup SSH Keys and known_hosts
      #   env:
      #       SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #   run: |
      #       ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #       ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: test-wego-add
        working-directory: ./test/acceptance/test
        with:
          GITHUB_ORG: weaveworks
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          go test -v -run TestWegoCoreOperations
